
export const CATEGORIES = [
  "Medications",
  "Vitamins",
  "Pain Relief",
  "Cold & Flu",
  "Digestive",
  "Skincare",
  "First Aid",
  "Baby Care",
  "Personal Care",
]

export const BRANDS = [
  "PharmaCare",
  "HealthPlus",
  "WellnessLab",
  "MediCare",
  "NaturalRx",
  "BioVita",
  "PureHealth",
  "LifeLine",
]

export const SPECIALIZATIONS = [
  "General Practitioner",
  "Cardiologist",
  "Dermatologist",
  "Pharmacist",
  "Nutritionist",
  "Psychiatrist",
  "Pediatrician",
  "Orthopedic",
]

export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Aspirin 500mg",
    description: "Effective pain relief and fever reducer",
    price: 5.99,
    image: "/images/aspirin.jpg",
    category: "Pain Relief",
    brand: "PharmaCare",
    inStock: true,
    rating: 4.5,
    reviews: 128,
    activeIngredients: "Acetylsalicylic Acid 500mg",
    instructions: "Take 1-2 tablets every 4-6 hours as needed, not exceeding 8 tablets per day",
    sideEffects: "May cause stomach upset or allergic reactions",
    dosage: "500mg per tablet",
  },
  {
    id: "2",
    name: "Vitamin C 1000mg",
    description: "Immune booster & powerful antioxidant",
    price: 12.99,
    image: "/images/vitamin-c.jpg",
    category: "Vitamins",
    brand: "HealthPlus",
    inStock: true,
    rating: 4.8,
    reviews: 256,
    activeIngredients: "Ascorbic Acid 1000mg",
    instructions: "Take 1 tablet daily with food",
    sideEffects: "Rare — may cause mild stomach discomfort",
    dosage: "1000mg per tablet",
  },
  {
    id: "3",
    name: "Cough & Cold Syrup",
    description: "Fast relief from cough, congestion & sore throat",
    price: 8.49,
    image: "/images/cough-syrup.jpg",
    category: "Cold & Flu",
    brand: "MediCare",
    inStock: true,
    rating: 4.3,
    reviews: 89,
    activeIngredients: "Dextromethorphan, Guaifenesin",
    instructions: "Adults: 10ml every 4-6 hours",
    sideEffects: "May cause drowsiness",
    dosage: "10ml per dose",
  },
  {
    id: "4",
    name: "Multivitamin Complex",
    description: "Complete daily nutritional support for men & women",
    price: 15.99,
    image: "/images/multivitamin.jpg",
    category: "Vitamins",
    brand: "WellnessLab",
    inStock: true,
    rating: 4.6,
    reviews: 312,
    activeIngredients: "Vitamin A, B-Complex, C, D, E + Minerals",
    instructions: "Take 1 tablet daily with breakfast",
    sideEffects: "Very rare when taken as directed",
    dosage: "1 tablet daily",
  },
  {
    id: "5",
    name: "Ibuprofen 400mg",
    description: "Strong anti-inflammatory pain relief",
    price: 7.49,
    image: "/images/ibuprofen.jpg",
    category: "Pain Relief",
    brand: "PharmaCare",
    inStock: false,
    rating: 4.7,
    reviews: 189,
    activeIngredients: "Ibuprofen 400mg",
    instructions: "Take 1 tablet every 6-8 hours with food",
    sideEffects: "Take with food to avoid stomach irritation",
    dosage: "400mg per tablet",
  },
  {
    id: "6",
    name: "Probiotic Digestive Support",
    description: "30 billion CFUs for gut health & immunity",
    price: 24.99,
    image: "/images/probiotic.jpg",
    category: "Digestive",
    brand: "NaturalRx",
    inStock: true,
    rating: 4.8,
    reviews: 201,
    activeIngredients: "Lactobacillus, Bifidobacterium + Prebiotics",
    instructions: "Take 1 capsule daily",
    sideEffects: "Mild bloating possible in first few days",
    dosage: "1 capsule",
  },
  {
    id: "7",
    name: "Antacid Chewable Tablets",
    description: "Fast relief from heartburn & acid reflux",
    price: 4.99,
    image: "/images/antacid.jpg",
    category: "Digestive",
    brand: "MediCare",
    inStock: true,
    rating: 4.2,
    reviews: 76,
    activeIngredients: "Calcium Carbonate 750mg",
    instructions: "Chew 1-2 tablets as needed",
    sideEffects: "May cause constipation if overused",
    dosage: "750mg per tablet",
  },
  {
    id: "8",
    name: "Hand Sanitizer 500ml",
    description: "70% alcohol — kills 99.9% of germs",
    price: 9.99,
    image: "/images/sanitizer.jpg",
    category: "First Aid",
    brand: "PureHealth",
    inStock: true,
    rating: 4.6,
    reviews: 412,
    activeIngredients: "Ethyl Alcohol 70%",
    instructions: "Apply generously to hands and rub until dry",
    sideEffects: "None",
    dosage: "As needed",
  },
]


export const MOCK_DOCTORS = [
  // Female Doctors
  {
    id: "doc-1",
    name: "Dr. Sarah Johnson",
    gender: "female",
    specialization: "General Practitioner",
    qualification: "MD, MRCGP",
    experience: 12,
    rating: 4.8,
    reviews: 234,
    patientsServed: 5200,
    phone: "+20 100 123 4567",
    email: "sarah.j@pharmtish.com",
    location: "New Cairo, Cairo",
    availability: "Mon-Fri, 9 AM - 5 PM",
    bio: "Compassionate family doctor specializing in preventive care and women's health.",
    image: "/images/female-doc.png",
    consultationFee: 200,
    languages: ["English", "Arabic", "French"],
  },
  {
    id: "doc-2",
    name: "Dr. Fatima Mahmoud",
    gender: "female",
    specialization: "Pediatrician",
    qualification: "MD, Pediatric Board",
    experience: 15,
    rating: 4.9,
    reviews: 512,
    patientsServed: 8900,
    phone: "+20 111 222 3344",
    email: "fatima.m@pharmtish.com",
    location: "Maadi, Cairo",
    availability: "Sat-Wed, 10 AM - 6 PM",
    bio: "Loving pediatrician with 15 years caring for children from newborns to teens.",
    image: "/images/female-doc.png",
    consultationFee: 250,
    languages: ["Arabic", "English"],
  },
  {
    id: "doc-3",
    name: "Dr. Nour Ahmed",
    gender: "female",
    specialization: "Dermatologist",
    qualification: "MD, MSc Dermatology",
    experience: 10,
    rating: 4.7,
    reviews: 387,
    patientsServed: 6100,
    phone: "+20 122 333 4455",
    email: "nour.a@pharmtish.com",
    location: "Nasr City, Cairo",
    availability: "Sun-Thu, 4 PM - 10 PM",
    bio: "Expert in acne, eczema, psoriasis, and cosmetic dermatology.",
    image: "/images/female-doc.png",
    consultationFee: 300,
    languages: ["Arabic", "English"],
  },
  {
    id: "doc-4",
    name: "Dr. Layla Hassan",
    gender: "female",
    specialization: "Gynecologist",
    qualification: "MD, OB-GYN",
    experience: 14,
    rating: 4.8,
    reviews: 428,
    patientsServed: 7200,
    phone: "+20 155 666 7788",
    email: "layla.h@pharmtish.com",
    location: "Mohandessin, Giza",
    availability: "Mon-Wed-Fri, 5 PM - 9 PM",
    bio: "Trusted women's health specialist focusing on pregnancy, fertility, and menopause.",
    image: "/images/female-doc.png",
    consultationFee: 350,
    languages: ["Arabic", "English"],
  },
  {
    id: "doc-5",
    name: "Dr. Mariam Youssef",
    gender: "female",
    specialization: "Nutritionist",
    qualification: "PhD Clinical Nutrition",
    experience: 9,
    rating: 4.6,
    reviews: 189,
    patientsServed: 3400,
    phone: "+20 100 888 9900",
    email: "mariam.y@pharmtish.com",
    location: "Heliopolis, Cairo",
    availability: "Sun-Tue-Thu, 11 AM - 7 PM",
    bio: "Helping patients achieve health goals through science-based nutrition plans.",
    image: "/images/female-doc.png",
    consultationFee: 200,
    languages: ["Arabic", "English", "German"],
  },

  // Male Doctors
  {
    id: "doc-6",
    name: "Dr. Ahmed Khalil",
    gender: "male",
    specialization: "Cardiologist",
    qualification: "MD, FACC",
    experience: 18,
    rating: 4.9,
    reviews: 412,
    patientsServed: 8200,
    phone: "+20 100 987 6543",
    email: "ahmed.k@pharmtish.com",
    location: "Zamalek, Cairo",
    availability: "Tue-Sat, 11 AM - 7 PM",
    bio: "Leading heart specialist in hypertension and interventional cardiology.",
    image: "/images/male-doc.png",
    consultationFee: 400,
    languages: ["Arabic", "English"],
  },
  {
    id: "doc-7",
    name: "Dr. Mohamed El-Sayed",
    gender: "male",
    specialization: "Orthopedic Surgeon",
    qualification: "MD, FRCS",
    experience: 20,
    rating: 4.8,
    reviews: 567,
    patientsServed: 9800,
    phone: "+20 111 555 7777",
    email: "mohamed.s@pharmtish.com",
    location: "Dokki, Giza",
    availability: "Mon-Thu, 6 PM - 10 PM",
    bio: "Expert in joint replacement, sports injuries, and spine surgery.",
    image: "/images/male-doc.png",
    consultationFee: 450,
    languages: ["Arabic", "English"],
  },
  {
    id: "doc-8",
    name: "Dr. Omar Farouk",
    gender: "male",
    specialization: "Neurologist",
    qualification: "MD, Neurology Board",
    experience: 13,
    rating: 4.7,
    reviews: 298,
    patientsServed: 5100,
    phone: "+20 122 888 9900",
    email: "omar.f@pharmtish.com",
    location: "Sheikh Zayed, 6th of October",
    availability: "Sun-Wed, 5 PM - 9 PM",
    bio: "Specialized in headaches, epilepsy, stroke recovery, and Parkinson's.",
    image: "/images/male-doc.png",
    consultationFee: 350,
    languages: ["Arabic", "English"],
  },
  {
    id: "doc-9",
    name: "Dr. Khaled Mansour",
    gender: "male",
    specialization: "ENT Specialist",
    qualification: "MD, ENT Surgery",
    experience: 16,
    rating: 4.6,
    reviews: 376,
    patientsServed: 6900,
    phone: "+20 100 444 5566",
    email: "khaled.m@pharmtish.com",
    location: "Alexandria",
    availability: "Sat-Wed, 4 PM - 10 PM",
    bio: "Expert in sinus, hearing loss, and throat disorders.",
    image: "/images/male-doc.png",
    consultationFee: 300,
    languages: ["Arabic", "English"],
  },
  {
    id: "doc-10",
    name: "Dr. Youssef Tarek",
    gender: "male",
    specialization: "Ophthalmologist",
    qualification: "MD, Eye Surgery",
    experience: 11,
    rating: 4.8,
    reviews: 445,
    patientsServed: 6200,
    phone: "+20 155 777 8899",
    email: "youssef.t@pharmtish.com",
    location: "Giza",
    availability: "Mon-Fri, 10 AM - 4 PM",
    bio: "Laser vision correction and cataract surgery specialist.",
    image: "/images/male-doc.png",
    consultationFee: 300,
    languages: ["Arabic", "English"],
  },
  {
    id: "doc-11",
    name: "Dr. Amr Salah",
    gender: "male",
    specialization: "Psychiatrist",
    qualification: "MD, Psychiatry",
    experience: 10,
    rating: 4.7,
    reviews: 267,
    patientsServed: 4100,
    phone: "+20 111 999 0000",
    email: "amr.s@pharmtish.com",
    location: "New Cairo",
    availability: "Sun-Thu, 6 PM - 10 PM",
    bio: "Helping patients with anxiety, depression, ADHD, and stress management.",
    image: "/images/male-doc.png",
    consultationFee: 350,
    languages: ["Arabic", "English"],
  },
  {
    id: "doc-12",
    name: "Dr. Hossam Reda",
    gender: "male",
    specialization: "Pharmacist",
    qualification: "PharmD, Clinical Pharmacist",
    experience: 8,
    rating: 4.9,
    reviews: 612,
    patientsServed: 12000,
    phone: "+20 100 555 6666",
    email: "hossam.r@pharmtish.com",
    location: "Nasr City, Cairo",
    availability: "Daily, 9 AM - 11 PM",
    bio: "Expert medication counseling and chronic disease management.",
    image: "/images/male-doc.png",
    consultationFee: 100,
    languages: ["Arabic", "English"],
  },
  // Add more as needed...
]

export const FAKE_ORDERS = [
  {
    id: "ORD-1001",
    customerName: "Ahmed Mohamed",
    email: "ahmed@example.com",
    items: [
      { name: "Panadol Extra 24 Tablets", quantity: 2, price: 45 },
      { name: "Vitamin C 1000mg", quantity: 1, price: 89 },
    ],
    total: 179,
    status: "delivered",
    createdAt: Date.now() - 86400000 * 3, // 3 days ago
    paymentMethod: "cash",
    shippingAddress: "123 El-Haram St, Giza",
  },
  {
    id: "ORD-1002",
    customerName: "Fatma Ali",
    email: "fatma@gmail.com",
    items: [
      { name: "Augmentin 1g 14 Tablets", quantity: 1, price: 165 },
      { name: "Brufen 600mg", quantity: 1, price: 38 },
    ],
    total: 203,
    status: "shipped",
    createdAt: Date.now() - 86400000 * 1,
    paymentMethod: "card",
    shippingAddress: "Nasr City, Cairo",
  },
  {
    id: "ORD-1003",
    customerName: "Omar Khaled",
    email: "omar.k@gmail.com",
    items: [
      { name: "Insulin Lantus Pen", quantity: 2, price: 420 },
      { name: "Glucophage 1000mg", quantity: 1, price: 72 },
    ],
    total: 912,
    status: "confirmed",
    createdAt: Date.now() - 3600000 * 5, // 5 hours ago
    paymentMethod: "wallet",
    shippingAddress: "Maadi, Cairo",
  },
  {
    id: "ORD-1004",
    customerName: "Nour Hassan",
    email: "nour99@yahoo.com",
    items: [
      { name: "Cataflam 50mg 20 Tablets", quantity: 3, price: 78 },
    ],
    total: 234,
    status: "pending",
    createdAt: Date.now() - 3600000 * 2,
    paymentMethod: "cash",
    shippingAddress: "Heliopolis, Cairo",
  },
  {
    id: "ORD-1005",
    customerName: "Sara Mahmoud",
    email: "sara.m@outlook.com",
    items: [
      { name: "Concor 5mg", quantity: 1, price: 95 },
      { name: "Lipitor 20mg", quantity: 1, price: 180 },
    ],
    total: 275,
    status: "cancelled",
    createdAt: Date.now() - 86400000 * 7,
    paymentMethod: "card",
    shippingAddress: "New Cairo",
  },
  {
    id: "ORD-1006",
    customerName: "Youssef Tarek",
    email: "youssef.t@gmail.com",
    items: [
      { name: "Royal Jelly 1000mg", quantity: 1, price: 290 },
      { name: "Omega-3 Fish Oil", quantity: 2, price: 135 },
    ],
    total: 560,
    status: "delivered",
    createdAt: Date.now() - 86400000 * 5,
    paymentMethod: "cash",
    shippingAddress: "6th of October",
  },
  {
    id: "ORD-1007",
    customerName: "Laila Osman",
    email: "laila.osman@hotmail.com",
    items: [
      { name: "Neurobion Ampoules", quantity: 1, price: 125 },
      { name: "Voltaren Emulgel 50g", quantity: 2, price: 89 },
    ],
    total: 303,
    status: "shipped",
    createdAt: Date.now() - 86400000 * 2,
    paymentMethod: "card",
    shippingAddress: "Mohandessin, Giza",
  },
  {
    id: "ORD-1008",
    customerName: "Mostafa Salem",
    email: "mostafa.salem@pharmacy.com",
    items: [
      { name: "Amaryl 4mg", quantity: 1, price: 98 },
      { name: "Glucophage XR 750mg", quantity: 1, price: 115 },
    ],
    total: 213,
    status: "pending",
    createdAt: Date.now() - 3600000 * 8,
    paymentMethod: "wallet",
    shippingAddress: "Alexandria",
  },
  {
    id: "ORD-1009",
    customerName: "Hana Ezzat",
    email: "hana.ezzat@gmail.com",
    items: [
      { name: "Cerave Moisturizing Cream 340g", quantity: 1, price: 420 },
      { name: "La Roche-Posay Sunscreen SPF50", quantity: 1, price: 580 },
    ],
    total: 1000,
    status: "confirmed",
    createdAt: Date.now() - 86400000 * 1,
    paymentMethod: "card",
    shippingAddress: "Sheikh Zayed",
  },
  {
    id: "ORD-1010",
    customerName: "Karim Adel",
    email: "karim.adel@work.com",
    items: [
      { name: "Panadol Night 20 Tablets", quantity: 1, price: 65 },
      { name: "Strepsils Honey & Lemon", quantity: 2, price: 48 },
      { name: "Otrivin Nasal Spray", quantity: 1, price: 72 },
    ],
    total: 233,
    status: "pending",
    createdAt: Date.now() - 3600000 * 1,
    paymentMethod: "cash",
    shippingAddress: "Dokki, Giza",
  },
]
export const MOCK_USERS = [
  {
    id: "user-1",
    name: "Ahmed Mohamed",
    email: "ahmed@example.com",
    joinDate: "2025-01-15",
    orders: 12,
    totalSpent: "2,450 L.E",
    status: "active",
  },
  {
    id: "user-2",
    name: "Fatma Ali",
    email: "fatma@gmail.com",
    joinDate: "2025-01-10",
    orders: 8,
    totalSpent: "1,890 L.E",
    status: "active",
  },
  {
    id: "user-3",
    name: "Omar Khaled",
    email: "omar.k@gmail.com",
    joinDate: "2025-01-08",
    orders: 15,
    totalSpent: "4,120 L.E",
    status: "vip",
  },
  {
    id: "user-4",
    name: "Nour Hassan",
    email: "nour99@yahoo.com",
    joinDate: "2025-01-05",
    orders: 3,
    totalSpent: "567 L.E",
    status: "new",
  },
  {
    id: "user-5",
    name: "Sara Mahmoud",
    email: "sara.m@outlook.com",
    joinDate: "2024-12-20",
    orders: 5,
    totalSpent: "980 L.E",
    status: "active",
  },
]