export const CATEGORIES = ["Medications", "Vitamins", "Pain Relief", "Cold & Flu", "Digestive", "Skincare", "First Aid"]
export const BRANDS = ["PharmaCare", "HealthPlus", "WellnessLab", "MediCare", "NaturalRx"]

export const SPECIALIZATIONS = [
  "General Practitioner",
  "Cardiologist",
  "Dermatologist",
  "Pharmacist",
  "Nutritionist",
  "Psychiatrist",
]

export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Aspirin 500mg",
    description: "Effective pain relief and fever reducer",
    price: 5.99,
    image: "/aspirin-tablet-bottle.jpg",
    category: "Pain Relief",
    brand: "PharmaCare",
    inStock: true,
    rating: 4.5,
    reviews: 128,
    activeIngredients: "Acetylsalicylic Acid 500mg",
    instructions: "Take 1-2 tablets every 4-6 hours as needed, not exceeding 8 tablets per day",
    sideEffects: "May cause stomach upset, heartburn, or allergic reactions in sensitive individuals",
    dosage: "500mg per tablet",
  },
  {
    id: "2",
    name: "Vitamin C 1000mg",
    description: "Immune system support and antioxidant",
    price: 12.99,
    image: "/vitamin-c-capsules.jpg",
    category: "Vitamins",
    brand: "HealthPlus",
    inStock: true,
    rating: 4.8,
    reviews: 256,
    activeIngredients: "Ascorbic Acid 1000mg",
    instructions: "Take 1 tablet daily with water, preferably with food",
    sideEffects: "Generally well tolerated. May cause mild gastric discomfort in some individuals",
    dosage: "1000mg per tablet",
  },
  {
    id: "3",
    name: "Cough & Cold Syrup",
    description: "Fast relief from cough and cold symptoms",
    price: 8.49,
    image: "/cough-syrup-bottle.jpg",
    category: "Cold & Flu",
    brand: "MediCare",
    inStock: true,
    rating: 4.3,
    reviews: 89,
    activeIngredients: "Dextromethorphan 10mg/5ml, Guaifenesin 100mg/5ml",
    instructions: "Take 10ml (2 teaspoons) every 4-6 hours, not exceeding 40ml per day",
    sideEffects: "May cause drowsiness or dizziness",
    dosage: "10ml per dose",
  },
  {
    id: "4",
    name: "Multivitamin Complex",
    description: "Complete daily nutritional support",
    price: 15.99,
    image: "/multivitamin-tablets.jpg",
    category: "Vitamins",
    brand: "WellnessLab",
    inStock: true,
    rating: 4.6,
    reviews: 312,
    activeIngredients: "Vitamin A, B-Complex, C, D, E, Minerals",
    instructions: "Take 1 tablet daily with breakfast",
    sideEffects: "Generally well tolerated when taken as directed",
    dosage: "1 tablet per day",
  },
  {
    id: "5",
    name: "Ibuprofen 400mg",
    description: "Anti-inflammatory pain reliever",
    price: 7.49,
    image: "/ibuprofen-tablets.jpg",
    category: "Pain Relief",
    brand: "PharmaCare",
    inStock: false,
    rating: 4.7,
    reviews: 189,
    activeIngredients: "Ibuprofen 400mg",
    instructions: "Take 1 tablet every 6-8 hours as needed, not exceeding 3 tablets per day",
    sideEffects: "May cause stomach upset. Take with food or milk",
    dosage: "400mg per tablet",
  },
  {
    id: "6",
    name: "Digestive Enzyme",
    description: "Supports healthy digestion",
    price: 11.99,
    image: "/digestive-enzyme-capsules.jpg",
    category: "Digestive",
    brand: "NaturalRx",
    inStock: true,
    rating: 4.4,
    reviews: 145,
    activeIngredients: "Amylase, Protease, Lipase",
    instructions: "Take 1 capsule with main meals",
    sideEffects: "Generally well tolerated. May cause mild nausea in sensitive individuals",
    dosage: "1 capsule per meal",
  },
  {
    id: "7",
    name: "Antacid Tablets",
    description: "Relief from heartburn and acidity",
    price: 4.99,
    image: "/antacid-tablets.jpg",
    category: "Digestive",
    brand: "MediCare",
    inStock: true,
    rating: 4.2,
    reviews: 76,
    activeIngredients: "Calcium Carbonate 500mg",
    instructions: "Chew 1-2 tablets as needed, not exceeding 7 tablets per day",
    sideEffects: "May cause constipation in some individuals",
    dosage: "500mg per tablet",
  },
  {
    id: "8",
    name: "First Aid Antiseptic",
    description: "Wound cleaning and prevention",
    price: 6.49,
    image: "/antiseptic-bottle.jpg",
    category: "First Aid",
    brand: "HealthPlus",
    inStock: true,
    rating: 4.5,
    reviews: 98,
    activeIngredients: "Povidone Iodine 10%",
    instructions: "Apply topically to clean wounds, cover if necessary",
    sideEffects: "May cause skin irritation in sensitive individuals",
    dosage: "Topical application",
  },
]

export const MOCK_DOCTORS = [
  {
    id: "doc-1",
    name: "Dr. Sarah Johnson",
    specialization: "General Practitioner",
    qualification: "MD, Board Certified",
    experience: 12,
    rating: 4.8,
    reviews: 234,
    patientsServed: 5000,
    phone: "+1-555-0101",
    email: "sarah.johnson@pharmacare.com",
    location: "New York, NY",
    availability: "Mon-Fri, 9 AM - 5 PM",
    bio: "Dr. Sarah Johnson is a compassionate general practitioner with over 12 years of experience in comprehensive patient care. Specializing in preventive medicine and chronic disease management.",
    image: "/placeholder.svg",
    expertise: [
      "General Health Checkup",
      "Chronic Disease Management",
      "Preventive Medicine",
      "Medication Review",
      "Health Counseling",
    ],
    qualifications: [
      "MD from Harvard Medical School",
      "Board Certified in Internal Medicine",
      "Certified in Preventive Medicine",
      "Advanced Life Support Certification",
    ],
    languages: ["English", "Spanish", "French"],
    consultationFee: 75,
    reviews: [
      {
        author: "John Smith",
        rating: 5,
        comment: "Excellent doctor! Very thorough and caring. Highly recommended.",
        date: "2 weeks ago",
      },
      {
        author: "Emma Davis",
        rating: 5,
        comment: "Great experience! Dr. Johnson took time to answer all my questions.",
        date: "1 month ago",
      },
    ],
  },
  {
    id: "doc-2",
    name: "Dr. Michael Chen",
    specialization: "Cardiologist",
    qualification: "MD, Board Certified",
    experience: 15,
    rating: 4.9,
    reviews: 312,
    patientsServed: 6200,
    phone: "+1-555-0102",
    email: "michael.chen@heartcare.com",
    location: "Los Angeles, CA",
    availability: "Tue-Sat, 10 AM - 6 PM",
    bio: "Dr. Michael Chen is a leading cardiologist with 15 years of expertise in cardiovascular diseases. He specializes in heart disease prevention, diagnosis, and management.",
    image: "/placeholder.svg",
    expertise: [
      "Cardiovascular Disease Management",
      "Hypertension Control",
      "Lipid Management",
      "Arrhythmia Treatment",
      "Preventive Cardiology",
    ],
    qualifications: [
      "MD from Stanford University",
      "Board Certified in Cardiology",
      "Interventional Cardiology Training",
      "Advanced Cardiac Life Support",
    ],
    languages: ["English", "Mandarin", "Cantonese"],
    consultationFee: 120,
    reviews: [],
  },
  {
    id: "doc-3",
    name: "Dr. Rachel Williams",
    specialization: "Dermatologist",
    qualification: "MD, Board Certified",
    experience: 10,
    rating: 4.7,
    reviews: 189,
    patientsServed: 4100,
    phone: "+1-555-0103",
    email: "rachel.williams@dermcare.com",
    location: "Chicago, IL",
    availability: "Mon-Thu, 9 AM - 4 PM",
    bio: "Dr. Rachel Williams is a skilled dermatologist specializing in both medical and cosmetic dermatology. She has expertise in treating various skin conditions.",
    image: "/placeholder.svg",
    expertise: [
      "Acne Treatment",
      "Eczema Management",
      "Skin Cancer Detection",
      "Anti-Aging Treatments",
      "Laser Therapy",
    ],
    qualifications: [
      "MD from Yale School of Medicine",
      "Board Certified in Dermatology",
      "Cosmetic Dermatology Fellowship",
      "Mohs Surgery Training",
    ],
    languages: ["English", "Italian"],
    consultationFee: 100,
    reviews: [],
  },
  {
    id: "doc-4",
    name: "Pharmacist David Patel",
    specialization: "Pharmacist",
    qualification: "PharmD, Licensed",
    experience: 8,
    rating: 4.6,
    reviews: 156,
    patientsServed: 3500,
    phone: "+1-555-0104",
    email: "david.patel@pharmacy.com",
    location: "Houston, TX",
    availability: "Daily, 8 AM - 8 PM",
    bio: "David Patel is a highly knowledgeable pharmacist with expertise in medication management and drug interactions. Available for consultation and medication advice.",
    image: "/placeholder.svg",
    expertise: [
      "Medication Review",
      "Drug Interaction Checking",
      "Prescription Counseling",
      "Chronic Disease Management",
      "Medication Therapy Management",
    ],
    qualifications: [
      "PharmD from University of Texas",
      "Licensed Pharmacy Professional",
      "Medication Therapy Management Certification",
      "Immunization Provider",
    ],
    languages: ["English", "Hindi", "Gujarati"],
    consultationFee: 40,
    reviews: [],
  },
  {
    id: "doc-5",
    name: "Dr. Emily Rodriguez",
    specialization: "Nutritionist",
    qualification: "MS, Registered Dietitian",
    experience: 9,
    rating: 4.5,
    reviews: 124,
    patientsServed: 2800,
    phone: "+1-555-0105",
    email: "emily.rodriguez@nutrition.com",
    location: "Miami, FL",
    availability: "Wed-Sat, 11 AM - 7 PM",
    bio: "Emily Rodriguez is a registered dietitian specializing in personalized nutrition plans. She helps patients achieve their health goals through proper nutrition.",
    image: "/placeholder.svg",
    expertise: [
      "Weight Management",
      "Diabetes Nutrition",
      "Heart Health Diets",
      "Metabolic Disorders",
      "Sports Nutrition",
    ],
    qualifications: [
      "MS in Nutrition from Boston University",
      "Registered Dietitian (RD)",
      "Certified Diabetes Educator",
      "Sports Nutrition Specialist",
    ],
    languages: ["English", "Spanish", "Portuguese"],
    consultationFee: 65,
    reviews: [],
  },
  {
    id: "doc-6",
    name: "Dr. James Wilson",
    specialization: "Psychiatrist",
    qualification: "MD, Board Certified",
    experience: 14,
    rating: 4.8,
    reviews: 267,
    patientsServed: 4900,
    phone: "+1-555-0106",
    email: "james.wilson@mentalhealth.com",
    location: "Seattle, WA",
    availability: "Mon-Fri, 10 AM - 6 PM",
    bio: "Dr. James Wilson is a compassionate psychiatrist with extensive experience in mental health treatment and medication management. Specialized in depression and anxiety disorders.",
    image: "/placeholder.svg",
    expertise: [
      "Depression Treatment",
      "Anxiety Disorders",
      "Bipolar Disorder Management",
      "Medication Management",
      "Psychotherapy",
    ],
    qualifications: [
      "MD from University of Washington",
      "Board Certified in Psychiatry",
      "Psychopharmacology Fellowship",
      "Family Therapy Training",
    ],
    languages: ["English", "German"],
    consultationFee: 150,
    reviews: [],
  },
]
