export interface Product {
  id: number
  name: string
  category: string
  brand: string
  price: number
  originalPrice?: number
  rating: number
  reviews: number
  image: string
  description: string
  dosage?: string
  usage?: string
  sideEffects?: string
  storage?: string
  inStock: boolean
  stockCount: number
  badge?: string
  tags: string[]
}

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Paracetamol 500mg",
    category: "medicines",
    brand: "HealthCare Plus",
    price: 12.99,
    originalPrice: 15.99,
    rating: 4.8,
    reviews: 124,
    image: "/paracetamol-medicine-bottle.png",
    description: "Effective pain relief and fever reducer for adults and children over 12 years.",
    dosage: "1-2 tablets every 4-6 hours, maximum 8 tablets in 24 hours",
    usage: "For headaches, muscle pain, arthritis, backache, toothaches, colds, and fevers",
    sideEffects: "Rare: skin rash, blood disorders. Stop use if allergic reaction occurs.",
    storage: "Store below 25°C in a dry place. Keep out of reach of children.",
    inStock: true,
    stockCount: 150,
    badge: "Best Seller",
    tags: ["pain relief", "fever", "headache", "paracetamol"],
  },
  {
    id: 2,
    name: "Vitamin D3 Tablets",
    category: "supplements",
    brand: "VitaMax",
    price: 24.99,
    rating: 4.9,
    reviews: 89,
    image: "/vitamin-d3-supplement-bottle.png",
    description: "High-strength Vitamin D3 supplement for bone health and immune support.",
    dosage: "One tablet daily with food",
    usage: "Supports bone health, immune function, and muscle strength",
    storage: "Store in a cool, dry place away from direct sunlight",
    inStock: true,
    stockCount: 200,
    badge: "New",
    tags: ["vitamin d", "bone health", "immune support", "supplements"],
  },
  {
    id: 3,
    name: "Digital Thermometer",
    category: "equipment",
    brand: "MediTech",
    price: 18.99,
    originalPrice: 22.99,
    rating: 4.7,
    reviews: 156,
    image: "/digital-medical-thermometer.png",
    description: "Fast and accurate digital thermometer with fever alarm and memory function.",
    usage: "Oral, rectal, or underarm temperature measurement",
    storage: "Store in protective case at room temperature",
    inStock: true,
    stockCount: 75,
    badge: "Sale",
    tags: ["thermometer", "temperature", "fever", "medical device"],
  },
  {
    id: 4,
    name: "Hand Sanitizer 500ml",
    category: "personal-care",
    brand: "CleanGuard",
    price: 8.99,
    rating: 4.6,
    reviews: 203,
    image: "/hand-sanitizer-bottle.png",
    description: "70% alcohol-based hand sanitizer that kills 99.9% of germs and bacteria.",
    usage: "Apply to hands and rub thoroughly until dry. Use when soap and water unavailable.",
    storage: "Store away from heat and flame. Keep container tightly closed.",
    inStock: true,
    stockCount: 300,
    tags: ["sanitizer", "hygiene", "antibacterial", "alcohol"],
  },
  {
    id: 5,
    name: "First Aid Kit",
    category: "first-aid",
    brand: "SafetyFirst",
    price: 34.99,
    originalPrice: 39.99,
    rating: 4.8,
    reviews: 67,
    image: "/first-aid-kit-medical-supplies.png",
    description: "Comprehensive first aid kit with essential medical supplies for home and travel.",
    usage: "For treating minor cuts, scrapes, burns, and injuries",
    storage: "Store in a cool, dry place. Check expiry dates regularly.",
    inStock: true,
    stockCount: 45,
    badge: "Popular",
    tags: ["first aid", "emergency", "bandages", "medical supplies"],
  },
  {
    id: 6,
    name: "Omega-3 Fish Oil",
    category: "supplements",
    brand: "OceanHealth",
    price: 29.99,
    rating: 4.9,
    reviews: 145,
    image: "/omega-3-capsules.png",
    description: "Premium omega-3 fish oil capsules for heart and brain health support.",
    dosage: "Take 1-2 capsules daily with meals",
    usage: "Supports cardiovascular health, brain function, and joint mobility",
    storage: "Store in refrigerator after opening to maintain freshness",
    inStock: true,
    stockCount: 120,
    badge: "Premium",
    tags: ["omega 3", "fish oil", "heart health", "brain health"],
  },
  {
    id: 7,
    name: "Ibuprofen 400mg",
    category: "medicines",
    brand: "PainAway",
    price: 14.99,
    rating: 4.7,
    reviews: 98,
    image: "/ibuprofen-bottle.png",
    description: "Anti-inflammatory pain reliever for muscle pain, headaches, and fever.",
    dosage: "1 tablet every 6-8 hours with food, maximum 3 tablets daily",
    usage: "For inflammation, muscle pain, headaches, dental pain, and fever",
    sideEffects: "May cause stomach upset. Take with food. Consult doctor if pregnant.",
    storage: "Store below 25°C. Keep in original packaging.",
    inStock: true,
    stockCount: 80,
    tags: ["ibuprofen", "anti-inflammatory", "pain relief", "fever"],
  },
  {
    id: 8,
    name: "Multivitamin Complex",
    category: "supplements",
    brand: "VitaMax",
    price: 19.99,
    rating: 4.5,
    reviews: 234,
    image: "/multivitamin-supplement-bottle.png",
    description: "Complete daily multivitamin with essential vitamins and minerals.",
    dosage: "One tablet daily with breakfast",
    usage: "Supports overall health, energy levels, and immune function",
    storage: "Store in a cool, dry place away from children",
    inStock: true,
    stockCount: 180,
    tags: ["multivitamin", "daily supplement", "energy", "immune support"],
  },
  {
    id: 9,
    name: "Blood Pressure Monitor",
    category: "equipment",
    brand: "MediTech",
    price: 89.99,
    originalPrice: 109.99,
    rating: 4.8,
    reviews: 76,
    image: "/digital-blood-pressure-monitor.png",
    description: "Automatic digital blood pressure monitor with large display and memory.",
    usage: "For monitoring blood pressure at home. Easy one-button operation.",
    storage: "Store in carrying case at room temperature",
    inStock: true,
    stockCount: 25,
    badge: "Professional",
    tags: ["blood pressure", "monitor", "hypertension", "medical device"],
  },
  {
    id: 10,
    name: "Antiseptic Cream",
    category: "first-aid",
    brand: "HealFast",
    price: 6.99,
    rating: 4.4,
    reviews: 167,
    image: "/antiseptic-cream-tube.png",
    description: "Antiseptic cream for minor cuts, scrapes, and skin infections.",
    usage: "Apply thin layer to affected area 2-3 times daily",
    storage: "Store below 25°C. Do not freeze.",
    inStock: true,
    stockCount: 95,
    tags: ["antiseptic", "wound care", "cuts", "healing"],
  },
]

export const categories = [
  { id: "all", name: "All Products", count: mockProducts.length },
  { id: "medicines", name: "Medicines", count: mockProducts.filter((p) => p.category === "medicines").length },
  { id: "supplements", name: "Supplements", count: mockProducts.filter((p) => p.category === "supplements").length },
  {
    id: "personal-care",
    name: "Personal Care",
    count: mockProducts.filter((p) => p.category === "personal-care").length,
  },
  { id: "equipment", name: "Equipment", count: mockProducts.filter((p) => p.category === "equipment").length },
  { id: "first-aid", name: "First Aid", count: mockProducts.filter((p) => p.category === "first-aid").length },
]

export const brands = Array.from(new Set(mockProducts.map((p) => p.brand))).sort()

export const sortOptions = [
  { value: "name-asc", label: "Name (A-Z)" },
  { value: "name-desc", label: "Name (Z-A)" },
  { value: "price-asc", label: "Price (Low to High)" },
  { value: "price-desc", label: "Price (High to Low)" },
  { value: "rating-desc", label: "Highest Rated" },
  { value: "popularity", label: "Most Popular" },
]

export const products = mockProducts
